import React, { useState, useEffect } from 'react'

const Test = () => {
    const [count, setCount] = useState(0)
    const [value, setValue] = useState(1)


    useEffect(() => {
        alert("Alert generated by a webpage onclick")
    }, [count])


    return (
        <>
            <center>
                <h2>{count}</h2>
                <button className="btn btn-warning" onClick={() => setCount(count + 1)}>Increase Count</button>
                <h2>{value}</h2>
                <button className="btn btn-info" onClick={() => setValue(value + 2)}>Increase value</button>
            </center>
        </>
    )
}

export default Test